name: q1
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.6.2.post1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.8.9
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.3
  - fonttools=4.51.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - glib=2.80.2
  - glib-tools=2.80.2
  - gst-plugins-base=1.22.9
  - gstreamer=1.22.9
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.0
  - hyperframe=6.0.1
  - icu=70.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - jpeg=9e
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.6
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libdeflate=1.17
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.47.0
  - libtiff=4.5.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxml2=2.12.7
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - msys2-conda-epoch=20160418
  - nbclassic=1.1.0
  - nbclient=0.10.1
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - notebook-shim=0.2.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ollama=0.1.17
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.4.0
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.43
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - ply=3.11
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=6.1.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2024.1
  - pywin32=307
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt-main=5.15.8
  - referencing=0.35.1
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.1
  - scikit-posthocs=0.11.0
  - scipy=1.14.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - tbb=2021.8.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.42.34433
  - vs2015_runtime=14.42.34433
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
