name: q1_audit
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.6.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - pyparsing=3.2.0
  - python=3.12.7
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tqdm=4.66.5
  - tzdata=2024b
  - unicodedata2=15.1.0
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
